name: Hugo-CI
on:
  push:
    branches:
      - main
    paths-ignore:
        '.github/**'

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hugo build
        run: |
          pwd
      # - name: hugo deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSHKEY }}
      #     port: ${{ secrets.SSHPORT }}
      #     script: |
      #       sudo rsync --recursive --delete --force --progress ${{ secrets.PUBLICCONTENTPATH }} ${{ secrets.DEPLOYPATH }}
      #       sudo nginx -s reload