name: build
on:
  push:
    branches:
      - main
    paths-ignore:
        '.github/**'
  # Triggers the workflow on pull
  pull_request:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: hugo build
        run: |
          mkdir -p docs-cloud-common/content/
          cp -r content/${{ env.PRODUCT }} docs-cloud-common/content/
          hugo --source docs-cloud-common --minify --config config.toml,ignore-total-config.toml