# Build and publish documentation

name: publish

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-runner]
    env:
      PRODUCT: rewriter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run and build Hugo
        run: |
          mkdir -p common/content/${{ env.PRODUCT }}
          cp -r java common/content/${{ env.PRODUCT }}
          cp -r net common/content/${{ env.PRODUCT }}
          cp _index.md common/content/${{ env.PRODUCT }}
          hugo --source common --minify --config config.toml,ignore-total-config.toml
      - name: Deploy sitemap
        uses: nogsantos/scp-deploy@master
        with:
          src: common/public/product-sitemap.xml
          host: ${{ secrets.DOCS_SSH_HOST }}
          remote: ${{ secrets.DOCS_SSH_DIR }}/sitemaps/${{ env.PRODUCT }}.xml
          user: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}

      - name: Deploy documentation
        uses: nogsantos/scp-deploy@master
        with:
          src: common/public/${{ env.PRODUCT }}
          host: ${{ secrets.DOCS_SSH_HOST }}
          remote: ${{ secrets.DOCS_SSH_DIR }}
          user: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}